sudo: false

language: node_js
node_js:
  - 6.9.4 # LTS.

services:
  - mongodb
  - redis-server

env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

install:
  - npm install
  - npm install -g codecov

script:
  - npm run coverage

after_success:
  - codecov